project:
  type: website

website:
  title: "website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: hanke_etal_2020_report.html
        text: Report
      - href: qc_report.html
        text: QC_report

resources:
  - hanke_etal_2020_report.html
  - qc_report.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



